import Head from 'next/head'
import { Inter } from '@next/font/google'
import Login from '../components/Login'
import Products from '../components/Products'
import { useEffect } from 'react'
import { useSelector } from 'react-redux'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
 
  const {token} = useSelector(state=>state.user)
  console.log("token ne",token);
  return (
    <>
      <Head>
        <title>Piton Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
      {!token || token ==="" || token === undefined ? <Login/>:<Products token={token} /> }
        
  
   
      </main>
    </>
  )
}
