import Head from 'next/head'
import { Inter } from '@next/font/google'
import Login from '../components/Login'
import Products from './products'
import { useEffect,useState } from 'react'
import { useSelector } from 'react-redux'
import {router} from "next/router"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
 
  const {token} = useSelector(state=>state.user)
  const [coin,setCoin]=useState(null)
  useEffect(()=>{
   setCoin(window.localStorage.getItem("token"))
  },[token])
  console.log("coin neydi",coin);
  return (
    <>
      <Head>
        
        <title>Piton Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
      {!coin  || coin ==="" || coin === undefined ? <Login/>:router.push("/products") }
        
  
   
      </main>
    </>
  )
}
