import Head from 'next/head'
import { Inter } from '@next/font/google'
import Login from '../components/Login'
import Products from './products'
import { useEffect } from 'react'
import { useSelector } from 'react-redux'
import {router} from "next/router"

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
 
  const {token} = useSelector(state=>state.user)
 
  return (
    <>
      <Head>
        <title>Piton Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
      {!token || token ==="" || token === undefined ? <Login/>:router.push("/products") }
        
  
   
      </main>
    </>
  )
}
